language: node_js
node_js:
    - 14.5.0

jobs:
    include:
        - stage: deploy
          script:
              - echo -e "depolying..."
          deploy:
              provider: npm
              email: "${EMAIL}"
              api_key: "${NPM_TOKEN}"
              on:
                  tags: true
branches:
    only:
        - tags
        # - masters
