language: node_js
node_js:
    - 14.5.0
#跳过默认的依赖下载和script脚本执行
install: skip
script: skip
stages:
  - name: deploy
jobs:
    include:
        - stage: deploy
          deploy:
              provider: npm
              email: "${EMAIL}"
              api_key: "${NPM_TOKEN}"
              on:
                  tags: true
branches:
      only:
        - /^v(\d+)\.(\d+)\.(\d+)$/
