language: node_js
node_js:
    - 14.5.0

jobs:
    include:
        - stage: deploy
          deploy:
              provider: npm
              email: "${EMAIL}"
              api_key: "${NPM_TOKEN}"
              on:
                  tags: true
branches:
      only:
        - /^v(\d+)\.(\d+)\.(\d+)$/
        # - master
